name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Re-create Android project
        run: flutter create --platforms=android --org=com.example .

      - name: Enable Core Library Desugaring & Java 8 in Android
        run: |
          BUILD_GRADLE="android/app/build.gradle"
          if [ -f "$BUILD_GRADLE" ]; then
            sed -i '/compileOptions {/a \        coreLibraryDesugaringEnabled true' $BUILD_GRADLE
            sed -i '/dependencies {/a \    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:2.0.4"' $BUILD_GRADLE
          fi

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate Launcher Icons
        run: flutter pub run flutter_launcher_icons

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
